### ISSUE TITLE
Update servicestack

### ISSUE THREAD

**Issue by konstrui** [danesparza/MailChimp.NET#153]
What should be done to update the project to use the newer ServiceStack?
I want to include this MailChimp code inside a webproject that already uses a newer ServiceStack. How should that work?

Best,
Daniel

**Comment by danesparza** [comment]
ServiceStack has been the bane of this project's existence.  :cry: 

So here's the skinny:  Past ServiceStack 3.9.71, ServiceStack is no longer 'free as in beer'.  It's only 'free as in speech'.  You have to pay for a license in order to use it legally in an app.  I didn't want to force those licensing restrictions on the users of this client library -- so I thought the best thing to do would be to limit the ServiceStack version that this shipped with.  

I'm considering removing ServiceStack.Text entirely, and just use the more native DataContractSerializer methods in .NET

All that aside, I think it would be pretty straightforward to [fork the repo](https://help.github.com/articles/fork-a-repo/) and upgrade the ServiceStack.Text implementation on your own.

**Comment by konstrui** [comment]
I understand. Maybe I'll do a fork. Just not so familiar with ServiceStack or e.g. NewtonSoft...

**Comment by konstrui** [comment]
OK, forked it and created a NuGet. This fork is based on ServiceStack 4.0.33.0
