### ISSUE TITLE
Plans for API v3 support?

### ISSUE THREAD

**Issue by hofo** [danesparza/MailChimp.NET#157]
Version 3 of the API has been recently released, deprecating the v2 API. Looks like there are some significant changes (I don't see how to get all members of a list, just the first 10). Do you have any thoughts about updating to support v3?

**Comment by danesparza** [comment]
Wow -- I didn't catch that.  Thanks for the heads up.  

It looks like you're right -- the v3 docs indicate you can only get the [first 10 members of a list](http://kb.mailchimp.com/api/resources/lists/members/lists-members-collection).

Also:  It looks like this version might introduce [OAuth based authentication](http://kb.mailchimp.com/api/article/about-oauth2).

**Comment by hofo** [comment]
I contacted API support via email and they said you had to page through
with similar parameters as the v2 API, though that's not clear from the v3
docs.

--
Howard Fore, howard.fore@hofo.com
A day without sunshine is like, you know, night. - Steve Martin

**Comment by SteveVaneeckhout** [comment]
If you want to receive all the members of a list at once you have to use the Export methods. The V2 api didn't return a full list either.

**Comment by proludio** [comment]
I guess I will ask the same question as the title of this, are there plans to update to match the 3.0 API.
I have not checked out the 2.0 code, (or the 3.0 code), so maybe this library already matches quite a bit of the 3.0 code?

**Comment by danesparza** [comment]
Yes -- I have plans to match the 3.0 API.  It will most likely be a complete re-write since MailChimp has [completely changed the API](http://kb.mailchimp.com/api/article/api-3-overview).  I'll most likely ditch ServiceStack.Text in favor for [newer native .NET JSON serialization methods](http://www.asp.net/web-api/overview/advanced/calling-a-web-api-from-a-net-client).  I'll still setup a build process and automatic NuGet package.

**Comment by proludio** [comment]
Timeframe, and would you like help?
