### ISSUE TITLE
Moving forward to Api 3?

### ISSUE THREAD

**Issue by Merryweather** [danesparza/MailChimp.NET#190]
Hi

Any plans for this library to support v3.0 since after 2016 the v.2.0 will be deprecated?

**Comment by technomaz** [comment]
Just to be clear, MailChimp API v2.0 is **already deprecated**. After 2016, it will no longer be supported. Which I assume means that unless this library begins to support 3.0, all calls using this will simply **fail**. We are 8.5 months away from that at this point.

**Comment by danesparza** [comment]
It sounds like [version 3 of the API should be pretty straightforward to use](http://developer.mailchimp.com/documentation/mailchimp/guides/get-started-with-mailchimp-api-3/).  I have no current plans to move forward with version 3 of the API, but I would welcome sensible pull requests.

**Comment by technomaz** [comment]
@danesparza - are you suggesting that the developers using this library plan to recode to use the API directly without a .NET wrapper? Are you not planning to move forward with v3 because you no longer use MailChimp API, you no longer have interest in the project, or you believe the v3 API should be used without a wrapper?
